package by.htp.trucking.controller;

public enum CommandName {
	MAIN_PAGE,
	SIGN_IN,
	SIGN_OUT,
	GET_PAGE_TO_CREATE_USER,
	GET_PAGE_TO_MAIN_USER,
	GET_PAGE_TO_CREATE_ORDER,
	GET_PAGE_TO_HISTORY_ORDER,
	GET_PAGE_TO_EDIT_USER,
	CREATE_USER,
	EDIT_USER,
	CREATE_ORDER,
	HISTORY_ORDER,
	FORGOT_PASSWORD,
	LOCALIZATION;
}
